import { test, expect } from '@playwright/test';

test('Initial HTML/CSS Tests', async ({ page }) => {
  await page.goto('/index.html');
  await page.waitForLoadState('domcontentloaded');

  await expect(page.getByRole('img', { name: 'UPSE logo' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Alumni Information Management System' })).toBeVisible();
  await expect(page.getByText('admin.up.edu.ph')).toBeVisible();
  await expect(page.locator('div').filter({ hasText: 'admin.up.edu.ph' })).toBeVisible();
  await expect(page.getByRole('img', { name: 'Logout icon' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Records', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Email Blast' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Add Records' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Alumni News' })).toBeVisible();
  // await expect(page.getByText('All')).toBeVisible();
  await page.locator('img').nth(2).click();
  await page.locator('img').nth(3).click();
  await page.locator('div').nth(2).click();
  await page.locator('img').nth(4).click();
  await page.getByRole('textbox', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search' }).fill('juan dela cruz');
  await page.getByRole('textbox', { name: 'Search' }).press('Enter');
  await page.locator('img').nth(5).click();
  await page.getByText('selected').click();
  await page.getByText('Name').click();
  await page.getByText('Sex').click();
  await page.getByText('Student No.').click();
  await page.getByText('Entry Date').click();
  await page.getByText('Active Organizations').click();
  await page.getByText('Employment History').click();
  await page.getByText('Graduate Info').click();
  await page.getByText('Action').click();
  await page.locator('div').filter({ hasText: 'Name Sex Student No. Entry' }).getByRole('checkbox').check();
  await page.locator('div').filter({ hasText: 'Name Sex Student No. Entry' }).getByRole('checkbox').uncheck();
  await page.getByRole('checkbox').nth(1).check();
  await page.getByRole('checkbox').nth(2).check();
  await page.getByRole('checkbox').nth(3).check();
  await page.getByRole('checkbox').nth(3).uncheck();
  await page.getByRole('checkbox').nth(2).uncheck();
  await page.getByRole('checkbox').nth(1).uncheck();
  await page.locator('.name-cell > img').first().click();
  await page.locator('.name-cell > img:nth-child(2)').first().click();
  await page.locator('.name-cell > img:nth-child(3)').first().click();
  await page.getByText('Juan Dela Cruz').first().click();
  await page.getByText('M', { exact: true }).first().click();
  await page.getByText('-99999').first().click();
  await page.getByText('-99999').first().click();
  await page.getByText('/2023').first().click();
  await page.getByText('UP CSI').first().click();
  await page.getByText('UP CURSOR').first().click();
  await page.getByText('Employer').first().click();
  await page.getByText('Position').first().click();
  await page.getByText('-2025').first().click();
  await page.locator('.work-cell > div > img').first().click();
  await page.locator('.work-cell > div:nth-child(3) > img').first().click();
  await page.locator('div:nth-child(4) > img').first().click();
  await page.getByText('BS Computer Science').first().click();
  await page.locator('div').filter({ hasText: 'Magna Cum Laude' }).nth(2).click();
  await page.getByText('Magna Cum Laude').first().click();
  await page.locator('.grad-cell > div > img').first().click();
  await page.locator('.grad-cell > div:nth-child(2) > img').first().click();
  await page.getByText('/2027').first().click();
  await page.locator('.grad-cell > div:nth-child(3) > img').first().click();
  await page.locator('div:nth-child(9) > img').first().click();
  await page.locator('div:nth-child(9) > img:nth-child(2)').first().click();
});